name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v1.2.3

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating releases

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Type check
      run: bun run typecheck

    - name: Build extension
      run: bun run build

    - name: Package ZIP for Chrome Web Store
      run: bun run package

    - name: Generate private key for CRX
      run: openssl genrsa -out private-key.pem 2048

    - name: Package CRX for direct installation
      run: |
        # Install chrome-webstore-upload-cli for CRX generation
        npm install -g crx3

        # Generate CRX file
        crx3 --keyPath=private-key.pem --xmlPath=updates.xml dist prayer-times-chrome.crx

    - name: Create updates.xml for auto-updates
      run: |
        cat > updates.xml << EOF
        <?xml version='1.0' encoding='UTF-8'?>
        <gupdate xmlns='http://www.google.com/update2/response' protocol='2.0'>
          <app appid='$(openssl rsa -in private-key.pem -pubout -outform DER | openssl dgst -sha256 -hex | cut -d' ' -f2 | cut -c1-32 | sed 's/./&/16' | tr '0-9a-f' 'a-p')'>
            <updatecheck codebase='https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/prayer-times-chrome.crx' version='${{ github.ref_name }}' />
          </app>
        </gupdate>
        EOF

    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Prayer Times Chrome Extension ${{ steps.version.outputs.VERSION }}
        body: |
          ## Prayer Times Chrome Extension ${{ steps.version.outputs.VERSION }}

          ### Installation Options:

          **🏪 Chrome Web Store (Recommended)**
          - Automatic updates
          - Verified by Google
          - Easy installation

          **📦 Direct Installation (.crx)**
          - Download `prayer-times-chrome.crx`
          - Open Chrome and go to `chrome://extensions/`
          - Enable "Developer mode"
          - Drag and drop the .crx file

          **🔧 Developer Installation (.zip)**
          - Download `prayer-times-chrome.zip`
          - Extract the ZIP file
          - Load unpacked extension in Chrome

          ### What's New:
          - Prayer time calculations for any location
          - Multiple Islamic calculation methods
          - GPS location support
          - Clean, modern interface

          ### Requirements:
          - Chrome 88+ (Manifest v3 support)

        draft: false
        prerelease: false

    - name: Upload ZIP to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./prayer-times-chrome.zip
        asset_name: prayer-times-chrome.zip
        asset_content_type: application/zip

    - name: Upload CRX to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./prayer-times-chrome.crx
        asset_name: prayer-times-chrome.crx
        asset_content_type: application/x-chrome-extension

    - name: Upload Updates XML
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./updates.xml
        asset_name: updates.xml
        asset_content_type: application/xml