name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v1.2.3

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating releases

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Type check
      run: bun run typecheck

    - name: Build extension
      run: bun run build

    - name: Package ZIP for Chrome Web Store
      run: bun run package

    - name: Setup CRX private key
      if: ${{ secrets.CRX_PRIVATE_KEY != '' }}
      run: |
        echo "${{ secrets.CRX_PRIVATE_KEY }}" > private-key.pem
        chmod 600 private-key.pem

    - name: Package CRX for direct installation
      if: ${{ secrets.CRX_PRIVATE_KEY != '' }}
      run: |
        # Install crx3 for CRX generation
        npm install -g crx3

        # Generate CRX file with persistent key
        crx3 dist --key private-key.pem

        # Rename the generated file to expected name
        mv web-extension.crx prayer-times-chrome.crx

        # Clean up private key
        rm -f private-key.pem

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Prayer Times Chrome Extension ${{ github.ref_name }}
        body: |
          ## Prayer Times Chrome Extension ${{ github.ref_name }}

          ### Installation Options:

          **🏪 Chrome Web Store (Recommended)**
          - Automatic updates
          - Verified by Google
          - Easy installation

          **📦 Direct Installation (.crx)**
          - Download `prayer-times-chrome.crx`
          - Open Chrome: `chrome://extensions/`
          - Enable "Developer mode"
          - Drag and drop the .crx file
          - Supports auto-updates from GitHub releases

          **🔧 Developer Installation (.zip)**
          - Download `prayer-times-chrome.zip`
          - Extract the ZIP file
          - Open Chrome: `chrome://extensions/`
          - Enable "Developer mode"
          - Click "Load unpacked" and select extracted folder

          ### Features:
          - Prayer time calculations for any location worldwide
          - Multiple Islamic calculation methods (MWL, ISNA, Egypt, etc.)
          - GPS location support with manual coordinate entry
          - Clean, modern interface optimized for Chrome
          - Countdown timer to next prayer
          - Settings persistence across browser sessions

          ### Requirements:
          - Chrome 88+ (Manifest v3 support)
          - No additional permissions beyond location and storage

        files: |
          prayer-times-chrome.zip
          prayer-times-chrome.crx
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}